export const USER_GRANT_TYPE = "Client Credentials"
export const CLIENT_ID = "l7xx0021410252cb4d6d98283affc14ee1a4"
export const CLIENT_SECRET = "ad68d46e80a04df9b401e5445ff4e947"
export const SCOPE = "CITYGUIDES DCIOFFERS DCIOFFERS_POST DCILOUNGES DCILOUNGES_POST DCILOUNGES_PROVIDER_LG" +
    " DCILOUNGES_PROVIDER_DCIPL DCI_ATM DCI_CURRENCYCONVERSION DCI_CUSTOMERSERVICE DCI_TIP"
export const TOKEN_URL = "https://api.discover.com/auth/oauth/v2/token"